version: '3'

services:
  server:
    build: ./minecraft-server
    image: abidingattempt/minecraft-server
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - "mc:/data"
    environment:
      EULA: "TRUE"
      CONSOLE: "false"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
      RCON_PORT: 25575
    restart: always
    stdin_open: TRUE
  # backup:
  #   build: ./minecraft-backup
  #   image: abidingattempt/minecraft-backup
  #   depends_on:
  #     - "server"
  #   volumes:
  #     - "mc:/data"
  #   environment:
  #     RCON_HOST: "server"
  #     RCON_PASSWORD: "minecraft"
  #     RCON_PORT: 25575    
  # rcon:
  #   image: itzg/rcon
  #   ports:
  #     - "4326:4326"
  #     - "4327:4327"
  #   volumes:
  #     - "rcon:/opt/rcon-web-admin/db"

volumes:
  mc:
  # rcon:
